// <auto-generated />
using System;
using Aula09ValidacaodeDados.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aula09ValidacaodeDados.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200818155919_CadastroMigration")]
    partial class CadastroMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aula09ValidacaodeDados.Models.Cadastro", b =>
                {
                    b.Property<int>("CadastroID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfirmarEmail");

                    b.Property<string>("Email");

                    b.Property<int>("Idade");

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome");

                    b.HasKey("CadastroID");

                    b.ToTable("Cadastros");
                });
#pragma warning restore 612, 618
        }
    }
}
